name: workflow.yml
on:
  push:
    branches:
      - main
    paths:
      - "backend/src/**"
      - ".github/workflows/workflow.yml"
      - "docker-compose.yml"
      - "init.sql"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Start postgres clean
        run: |
          docker compose down -v
          docker compose up -d 

      - name: Wait for postgres to be healthy
        run: sleep 5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - working-directory: ./backend
        run: chmod +x gradlew

      - name: Build grade
        working-directory: ./backend
        run: ./gradlew test
        env:
          GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}